In [90]:
import numpy as np
import pandas as pd

In [91]:
data = pd.read_csv("outlier.csv")
data

1    10   30
0     2  2002   35
1     3    30   40
2     4    40   45
3     5    50   50
4     6    60   55
5  1000    70   60
6     8    80   65
7     9    90  707
8    10   100   75

In [92]:
arr = np.array(data)
arr

array([[   2, 2002,   35],
       [   3,   30,   40],
       [   4,   40,   45],
       [   5,   50,   50],
       [   6,   60,   55],
       [1000,   70,   60],
       [   8,   80,   65],
       [   9,   90,  707],
       [  10,  100,   75]], dtype=int64)

In [93]:
Q1 = np.quantile(arr, [.25])
Q2=  np.quantile(arr, [.5])
Q3=  np.quantile(arr, [.75])

In [94]:
iqr= Q3- Q1
iqr

array([63.])

In [95]:
a=arr>(Q1 - iqr*1.5)
a


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [125]:
c= (arr<(Q2+ 1.5*iqr)).all(axis=1).reshape(9,1)
c


array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True]])

In [144]:
any((arr & c))


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [143]:
((arr*c)==1).all(axis=1)

array([False, False, False, False, False, False, False, False, False])