In [1]:
import numpy as np

In [10]:
rng = np.random.default_rng()
x = np.arange(6, 16)
rand = rng.random(size = 10)
y = x**2 + rand
arr = np.column_stack((x,y))

In [11]:
arr

array([[  6.        ,  36.29710347],
       [  7.        ,  49.53671118],
       [  8.        ,  64.01811489],
       [  9.        ,  81.45882399],
       [ 10.        , 100.58114402],
       [ 11.        , 121.21884305],
       [ 12.        , 144.10465538],
       [ 13.        , 169.70732345],
       [ 14.        , 196.80621516],
       [ 15.        , 225.29325806]])

In [12]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2, include_bias = False)
res = poly.fit_transform(arr[:, [0]])
res

array([[  6.,  36.],
       [  7.,  49.],
       [  8.,  64.],
       [  9.,  81.],
       [ 10., 100.],
       [ 11., 121.],
       [ 12., 144.],
       [ 13., 169.],
       [ 14., 196.],
       [ 15., 225.]])

In [14]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(res, arr[:, 1])

LinearRegression()

In [15]:
reg.coef_

array([-0.02522383,  1.00231893])

In [16]:
reg.intercept_

0.39227646824944884

In [18]:
reg.predict(res)

array([ 36.32441491,  49.32933715,  64.33889724,  81.35309519,
       100.371931  , 121.39540467, 144.42351619, 169.45626558,
       196.49365281, 225.53567791])