scaling

In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame({'c1': np.arange(10), 'c2': np.arange(1000, 1010)})
df

c1    c2
0   0  1000
1   1  1001
2   2  1002
3   3  1003
4   4  1004
5   5  1005
6   6  1006
7   7  1007
8   8  1008
9   9  1009

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df[['c1', 'c2']])

StandardScaler()

In [8]:
scaler.mean_

array([   4.5, 1004.5])

In [9]:
scaler.var_

array([8.25, 8.25])

In [5]:
scaler.transform(df[['c1', 'c2']])

array([[-1.5666989 , -1.5666989 ],
       [-1.21854359, -1.21854359],
       [-0.87038828, -0.87038828],
       [-0.52223297, -0.52223297],
       [-0.17407766, -0.17407766],
       [ 0.17407766,  0.17407766],
       [ 0.52223297,  0.52223297],
       [ 0.87038828,  0.87038828],
       [ 1.21854359,  1.21854359],
       [ 1.5666989 ,  1.5666989 ]])