In [38]:
import numpy as np
import pandas as pd

# Numpy statistics

## Order statistics

In [39]:
arr = np.array([[2, 4, 9, 1], [6, 9, 1, 3]])
arr

array([[2, 4, 9, 1],
       [6, 9, 1, 3]])

In [40]:
# range of values 
np.ptp(arr)

8

In [41]:
np.ptp(arr, axis=0)

array([4, 5, 8, 2])

In [42]:
np.ptp(arr, axis=1)

array([8, 8])

In [43]:
# Quantile 
arx = np.array([1, 3, 7, 9, 12, 15, 18, 21])
arx

array([ 1,  3,  7,  9, 12, 15, 18, 21])

In [44]:
np.quantile(arx, [.25, .75])

array([ 6.  , 15.75])

In [45]:
np.quantile(arr, 0.5, axis=0)

array([4. , 6.5, 5. , 2. ])

In [46]:
# Percentile
np.percentile(arx, [25, 75])

array([ 6.  , 15.75])

In [47]:
np.percentile(arr, 50, axis=0)

array([4. , 6.5, 5. , 2. ])

## Averages and variances 

In [48]:
arx

array([ 1,  3,  7,  9, 12, 15, 18, 21])

In [49]:
np.mean(arx)

10.75

In [50]:
np.median(arx)

10.5

In [51]:
np.std(arx)

6.609652033201143

In [52]:
np.std(arx, ddof=1)

7.066015244009273

In [53]:
np.var(arx)

43.6875

In [54]:
np.var(arx, ddof=1)

49.92857142857143

# Histograms

In [55]:
arr = np.array([3, 5, 8, 9, 13, 15, 21, 25, 27])
arr

array([ 3,  5,  8,  9, 13, 15, 21, 25, 27])

In [58]:
np.histogram(arr, bins=5)

(array([2, 2, 2, 1, 2]), array([ 3. ,  7.8, 12.6, 17.4, 22.2, 27. ]))

In [61]:
np.histogram_bin_edges(arr, bins=5)

array([ 3. ,  7.8, 12.6, 17.4, 22.2, 27. ])